### PR TITLE
Ruler Object Storage Migration Tool

### PR DESCRIPTION
**Pull request by jtlisi**
Add a ruler migration tool that will convert a object storage bucket of non-encoded rules to an encoded bucket.

### CODE REVIEW

**Comment by cstyan** [comment]
I don't see any encoding. Is it just this key that's being generated and used to name the bucket?

**Comment by jtlisi** [comment]
@cstyan Yea it's just the key name

**Comment by jtlisi** [comment]
@cstyan This should be ready for a look

**Comment by jtlisi** [comment]
@cstyan this script only exists to apply the encoding. Otherwise cortex will not consider the keys valid. However, I see your point that this tool might be useful to do a generic migration as well, not just upgrade from the old key encoding to the new one. I can add the encoding as a boolean flag.

**Pull request merged**
