### PR TITLE
Close res.Body

### PR DESCRIPTION
**Pull request by AllenzhLi**
Not close res.Body will resulting in goroutine leak.

### CODE REVIEW

**Review by tomwilkie — APPROVED** [review]

**Comment by tomwilkie** [comment]
Thanks @AllenzhLi!

**Review by gotjosh — APPROVED** [review]
LGTM! I think we can get rid of the defer statement given it is the last thing we do before closing the body.

Other than that, this is ready for a merge.

**Comment by AllenzhLi** [comment]
Updated.

**Review by jtlisi — APPROVED** [review]
LGTM

**Comment by gotjosh** [comment]
@AllenzhLi thank you very much for your contribution.

**Pull request merged**
