### PR TITLE
Update Cortex to 1.2.0

### PR DESCRIPTION
**Pull request by pstibrany**
Signed-off-by: Peter Štibraný <peter.stibrany@grafana.com>

### CODE REVIEW

**Comment by gouthamve** [comment]
Can we bump this to 1.3.0 now?

**Comment by pstibrany** [comment]
> Can we bump this to 1.3.0 now?

I don't mind, but there is some reluctance to updating vendored Cortex in this repo, due to missing tests :(

**Comment by pstibrany** [comment]
There are some incompatible changes in Cortex 1.3 (removal of `ruler/legacy_rulefmt` package) that need to be resolved. I don't have time fixing that at the moment, but if anyone wants to overtake this PR, feel free.

**Comment by pstibrany** [comment]
Obsoleted by #79.

**Pull request closed without merging**
