### PR TITLE
Add test for buildRequest with an already-escaped path

### PR DESCRIPTION
**Pull request by justincmoy**

### CODE REVIEW

**Comment by jtlisi** [comment]
@justincmoy Are you running into an issue with double escaping? Are you already setting your rule groups and rule namespaces to be escaped in the file?

**Comment by simonswine** [comment]
@justincmoy I have just seen your PR, after some investigation into the problem myself. Let me know if #140 fixes the double escaping you are experiencing

**Comment by justincmoy** [comment]
@simonswine Yup #140 fixes the issue for me. Thanks for looking into it!

**Comment by justincmoy** [comment]
By the way, I think I missed linking this PR with the issue. I'll close https://github.com/grafana/cortex-tools/issues/132 too.

**Pull request closed without merging**
