### PR TITLE
Parse multiple YAML rules documents

### PR DESCRIPTION
**Pull request by justincmoy**

### CODE REVIEW

**Review by jtlisi — COMMENTED** [review]
**nit[blocking]:** Please add a changelog entry.

Otherwise, LGTM

**Comment by justincmoy** [comment]
> **nit[blocking]:** Please add a changelog entry.
> 
> Otherwise, LGTM

Added.

**Review by simonswine — APPROVED** [review]
LGTM

**Comment by simonswine** [comment]
Thanks @justincmoy that's quite useful to me. Will prepare a release shortly :slightly_smiling_face:

**Pull request merged**
