### PR TITLE
Update grafana-tools/sdk to latest version

### PR DESCRIPTION
**Pull request by hjet**
`cortextool analyse grafana` fails on certain dashboards that use templating and/or panel heights due to unmarshalling errors with the underlying [grafana-tools/sdk](https://github.com/grafana-tools/sdk/) library. Notably, the command fails on kubernetes-mixin dashboards.

See https://github.com/grafana-tools/sdk/issues/130 for an example failure case and gist containing dashboards (same error). 

https://github.com/grafana-tools/sdk/pull/141 fixes the panel height issue and https://github.com/grafana-tools/sdk/pull/151 (just merged) fixes the templating issue.

This PR updates the library to point to latest master to capture these fixes.

cc @devinrcheevers @gouthamve

### CODE REVIEW

**Comment by gotjosh** [comment]
Hi @hjet! Which binary is this affecting?

**Comment by hjet** [comment]
hey @gotjosh!! my bad, requested a review by accident before this was ready to go 🙃 

i will add more context when it's ready for review, but tldr for now is it affects both `v0.10.1` and `main`:

`cortextool analyse grafana` errors out on any dashboard with templating or a defined panel height due to JSON unmarshalling errors. the main fixes are in https://github.com/grafana-tools/sdk

will add the failure case here before pinging for review

**Comment by hjet** [comment]
@gotjosh updated PR description, let me know if any questions

**Review by gouthamve — APPROVED** [review]
LGTM

**Pull request merged**
